apiVersion: v1
kind: Service
metadata:
  name: autodeploy-service
spec:
  selector:
    app: autodeploy-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
